export const ROUTES = Object.freeze({
	LANDING: "/",
	SIGN_IN: "/sign-in",
	SIGN_UP: "/sign-up",
	PASSWORD_RESET: "/password-reset",
	DEV_ROLE_SWITCH: "/dev/switch-role",
	FORBIDDEN: "/403",
	NOT_FOUND: "*",

	JOBS: "/jobs",
	JOB_DETAIL: (id = ":id") => `/jobs/${id}`,
	ME: "/me",
	MY_APPLICATION: (id = ":id") => `/me/applications/${id}`,
	MY_PROFILE: "/me/profile",
	MY_INBOX: "/me/inbox",
	HM_HOME: "/hm",
	HM_JOBS: "/hm/jobs",
	HM_JOB_NEW: "/hm/jobs/new",
	HM_JOB_EDIT: (id = ":id") => `/hm/jobs/${id}/edit`,
	HM_SCREENING: (id = ":id") => `/hm/jobs/${id}/screening`,
	HM_APPLICATION: (id = ":id") => `/hm/applications/${id}`,
	HM_SCHEDULE: (id = ":id") => `/hm/applications/${id}/schedule`,
	HM_OFFER: (id = ":id") => `/hm/applications/${id}/offer`,
	HM_INTERVIEWS: "/hm/interviews",
	HM_SCORESHEET: (id = ":id") => `/hm/interviews/${id}/scoresheet`,
	ADMIN_HOME: "/admin",
	ADMIN_JOBS: "/admin/jobs",
	ADMIN_FUNNEL: "/admin/funnel",
	ADMIN_TIME_TO_HIRE: "/admin/time-to-hire",
	ADMIN_AUDIT: "/admin/audit",
	ADMIN_SETTINGS: "/admin/settings",
});
