export const ROUTES = Object.freeze({
	LANDING: "/",
	SIGN_IN: "/sign-in",
	SIGN_UP: "/sign-up",
	PASSWORD_RESET: "/password-reset",
	DEV_ROLE_SWITCH: "/dev/switch-role",
	FORBIDDEN: "/403",
	NOT_FOUND: "*",

	APPLICANT_HOME: "/applicant/jobs",
	APPLICANT_JOBS: "/applicant/jobs",
	APPLICANT_JOB_DETAIL: (id = ":id") => `/applicant/jobs/${id}`,
	APPLICANT_APPLICATIONS: "/applicant/applications",
	APPLICANT_APPLICATION: (id = ":id") =>
		`/applicant/applications/${id}`,
	APPLICANT_MESSAGES: "/applicant/messages",
	APPLICANT_INTERVIEWS: "/applicant/interviews",
	APPLICANT_PROFILE: "/applicant/profile",

	DASHBOARD: "/dashboard",
	JOB_LISTINGS: "/job-listings",
	JOB_DETAIL: (id = ":id") => `/job-listings/${id}`,
	CANDIDATES: "/candidates",
	INTERVIEWS: "/interviews",
	INTERVIEW_FEEDBACK: (id = ":id") => `/interviews/${id}/feedback`,
	OFFERS: "/offers",
	AI_SCREENING: "/ai-screening",
	ANALYTICS: "/analytics",
	MESSAGES: "/messages",
	NOTIFICATIONS: "/notifications",
	TEAM_MANAGEMENT: "/team-management",
	AUDIT_LOGS: "/audit-logs",
	ORGANIZATION_SETTINGS: "/organization-settings",

	LEGACY_HM_HOME: "/hm",
	LEGACY_ADMIN_HOME: "/admin",
});
