export const SIM_TICK_MS = 5000;

export const SIM_STAGE_DURATIONS_MS = Object.freeze({
	APPLIED_TO_SCREENING: 8000,
	SCREENING_TO_DECISION: 12000,
	INTERVIEW_TO_DECISION: 20000,
	OFFER_TO_HIRED: 15000,
});

export const SIM_AI_DELAY_MS = 6000;

export const SIMULATION_ENABLED = true;
