name: Deploy Frontend

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop old container
        run: docker rm -f hireflow-frontend || true

      - name: Build frontend image
        run: docker build -t hireflow-frontend ./hireflow

      - name: Start hireflow-frontend container
        run: |
          docker run -d \
            --name hireflow-frontend \
            -p 3000:80 \
            frontend-app
