name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop old container
        run: docker rm -f frontend || true

      - name: Build frontend image
        run: docker build -t hireflow-frontend .

      - name: Start frontend container
        run: |
          docker run -d \
            --name frontend \
            -p 3000:80 \
            hireflow-frontend
